name: Vivado_CI_diff

on:
  push:
    branches-ignore: [ "main" ]

jobs:
  Vivado_CI_diff:

    runs-on: [make, vivado]

    steps:
    - uses: actions/checkout@v4

    - name: Get difference
      shell: bash
      run: |
        echo ".PHONY: ci_vivado_run" > ___diff
        echo "ci_vivado_run:" >> ___diff
        echo "	@> ___CI_REPORT;" >> ___diff
        git diff main -- ci_run | grep -E "^\+.*\(MAKE\) vivado" | sed "s/^+//g" >> ___diff
        mv ___diff ci_run

    - name: Simulate
      shell: bash
      run: |
        git submodule update --init --recursive --depth 1
        make CI

    - name: Fail if Simulation Contains Fails
      shell: bash
      run: |
        [[ -s ___CI_ERROR ]] && exit 1 || exit 0
